# Generated by Django 4.1.2 on 2022-10-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="credit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
