# Generated by Django 4.1.2 on 2022-10-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userdetail_credit_userdetail_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="credit",
            field=models.IntegerField(default=10),
        ),
    ]
