# Generated by Django 4.1.2 on 2022-10-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_userdetail_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symbols",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=100)),
                ("represent", models.CharField(max_length=50)),
                ("reward", models.IntegerField()),
            ],
        ),
    ]
